# Generated by Django 3.0.3 on 2020-02-06 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='slug',
            field=models.SlugField(default='hello'),
            preserve_default=False,
        ),
    ]
