# Generated by Django 3.0.3 on 2020-02-10 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_auto_20200210_1408'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='posts',
            options={'ordering': ['-publish_date', '-updated', '-timestamp']},
        ),
    ]
